LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= qrngd.c
LOCAL_SHARED_LIBRARIES := libc libcutils
LOCAL_CFLAGS := -DANDROID_CHANGES
LOCAL_MODULE = qrngd
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)
