/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ***   To edit the content of this header, modify the corresponding
 ***   source file (e.g. under external/kernel-headers/original/) then
 ***   run bionic/libc/kernel/tools/update_all.py
 ***
 ***   Any manual change here will be lost the next time this script will
 ***   be run. You've been warned!
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef BLTSVILLE_H
#define BLTSVILLE_H
#include "ocd.h"
#include "bverror.h"
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#include "bvblend.h"
#include "bvfilter.h"
#include "bvbuffdesc.h"
#include "bvcache.h"
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#include "bventry.h"
#include "bvsurfgeom.h"
struct bvrect {
 int left;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 int top;
 unsigned int width;
 unsigned int height;
};
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_OP_SHIFT 0
#define BVFLAG_OP_MASK (0xF << BVFLAG_OP_SHIFT)
#define BVFLAG_ROP (0x1 << BVFLAG_OP_SHIFT)  
#define BVFLAG_BLEND (0x2 << BVFLAG_OP_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_FILTER (0x4 << BVFLAG_OP_SHIFT)  
#define BVFLAG_KEY_SRC 0x00000010  
#define BVFLAG_KEY_DST 0x00000020  
#define BVFLAG_CLIP 0x00000040  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_SRCMASK 0x00000080  
#define BVFLAG_ASYNC 0x00000100  
#define BVFLAG_TILE_SRC1 0x00000200  
#define BVFLAG_TILE_SRC2 0x00000400  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_TILE_MASK 0x00000800  
#define BVFLAG_BATCH_SHIFT 12
#define BVFLAG_BATCH_MASK (3 << BVFLAG_BATCH_SHIFT)
#define BVFLAG_BATCH_NONE (0 << BVFLAG_BATCH_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_BATCH_BEGIN (1 << BVFLAG_BATCH_SHIFT)  
#define BVFLAG_BATCH_CONTINUE (2 << BVFLAG_BATCH_SHIFT)  
#define BVFLAG_BATCH_END (3 << BVFLAG_BATCH_SHIFT)  
#define BVFLAG_HORZ_FLIP_SRC1 0x00004000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_VERT_FLIP_SRC1 0x00008000  
#define BVFLAG_HORZ_FLIP_SRC2 0x00010000  
#define BVFLAG_VERT_FLIP_SRC2 0x00020000  
#define BVFLAG_HORZ_FLIP_MASK 0x00040000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVFLAG_VERT_FLIP_MASK 0x00080000  
#define BVFLAG_SCALE_RETURN 0x00100000  
#define BVFLAG_DITHER_RETURN 0x00200000  
#define BVIMPL_ANY 0
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVIMPL_FIRST_HW (1 << 31)  
#define BVIMPL_FIRST_CPU (1 << 0)  
#define BVSCALEDEF_VENDOR_SHIFT 24
#define BVSCALEDEF_VENDOR_MASK (0xFF << BVSCALEDEF_VENDOR_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_VENDOR_ALL (0 << BVSCALEDEF_VENDOR_SHIFT)
#define BVSCALEDEF_VENDOR_TI (1 << BVSCALEDEF_VENDOR_SHIFT)
#define BVSCALEDEF_VENDOR_GENERIC (0xFF << BVSCALEDEF_VENDOR_SHIFT)
#define BVSCALEDEF_CLASS_SHIFT 22
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_IMPLICIT (0 << BVSCALEDEF_CLASS_SHIFT)
#define BVSCALEDEF_EXPLICIT (1 << BVSCALEDEF_CLASS_SHIFT)
#define BVSCALEDEF_CLASS_MASK (3 << BVSCALEDEF_CLASS_MASK)
#define BVSCALEDEF_QUALITY_SHIFT 16
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_FASTEST (0x00 << BVSCALEDEF_QUALITY_SHIFT)
#define BVSCALEDEF_GOOD (0x15 << BVSCALEDEF_QUALITY_SHIFT)
#define BVSCALEDEF_BETTER (0x2A << BVSCALEDEF_QUALITY_SHIFT)
#define BVSCALEDEF_BEST (0x3F << BVSCALEDEF_QUALITY_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_QUALITY_MASK (0x3F << BVSCALEDEF_QUALITY_MASK)
#define BVSCALEDEF_TECHNIQUE_SHIFT 8
#define BVSCALEDEF_DONT_CARE (0x0 << BVSCALEDEF_TECHNIQUE_SHIFT)
#define BVSCALEDEF_NOT_NEAREST_NEIGHBOR (0x1 << BVSCALEDEF_TECHNIQUE_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_POINT_SAMPLE (0x2 << BVSCALEDEF_TECHNIQUE_SHIFT)
#define BVSCALEDEF_INTERPOLATED (0x3 << BVSCALEDEF_TECHNIQUE_SHIFT)
#define BVSCALEDEF_TECHNIQUE_MASK (0xF << BVSCALEDEF_TECHNIQUE_SHIFT)
#define BVSCALEDEF_TYPE_SHIFT 0
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_PHOTO (1 << BVSCALEDEF_TYPE_SHIFT)
#define BVSCALEDEF_DRAWING (2 << BVSCALEDEF_TYPE_SHIFT)
#define BVSCALEDEF_TYPE_MASK (3 << BVSCALEDEF_TYPE_MASK)
#define BVSCALEDEF_HORZ_SHIFT 8
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_HORZ_MASK (0xFF << BVSCALEDEF_HORZ_SHIFT)
#define BVSCALEDEF_VERT_SHIFT 0
#define BVSCALEDEF_VERT_MASK (0xFF << BVSCALEDEF_VERT_SHIFT)
#define BVSCALEDEF_NEAREST_NEIGHBOR 0x00
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_LINEAR 0x01
#define BVSCALEDEF_CUBIC 0x02
#define BVSCALEDEF_3_TAP 0x03
#define BVSCALEDEF_5_TAP 0x05
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVSCALEDEF_7_TAP 0x07
#define BVSCALEDEF_9_TAP 0x09
enum bvscalemode {
 BVSCALE_FASTEST = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_DONT_CARE,
 BVSCALE_FASTEST_NOT_NEAREST_NEIGHBOR = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_NOT_NEAREST_NEIGHBOR,
 BVSCALE_FASTEST_POINT_SAMPLE = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_POINT_SAMPLE,
 BVSCALE_FASTEST_INTERPOLATED = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_INTERPOLATED,
 BVSCALE_FASTEST_PHOTO = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_PHOTO,
 BVSCALE_FASTEST_DRAWING = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_FASTEST |
 BVSCALEDEF_DRAWING,
 BVSCALE_GOOD = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_GOOD |
 BVSCALEDEF_DONT_CARE,
 BVSCALE_GOOD_POINT_SAMPLE = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_GOOD |
 BVSCALEDEF_POINT_SAMPLE,
 BVSCALE_GOOD_INTERPOLATED = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_GOOD |
 BVSCALEDEF_INTERPOLATED,
 BVSCALE_GOOD_PHOTO = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_GOOD |
 BVSCALEDEF_PHOTO,
 BVSCALE_GOOD_DRAWING = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_GOOD |
 BVSCALEDEF_DRAWING,
 BVSCALE_BETTER = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BETTER |
 BVSCALEDEF_DONT_CARE,
 BVSCALE_BETTER_POINT_SAMPLE = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BETTER |
 BVSCALEDEF_POINT_SAMPLE,
 BVSCALE_BETTER_INTERPOLATED = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BETTER |
 BVSCALEDEF_INTERPOLATED,
 BVSCALE_BETTER_PHOTO = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BETTER |
 BVSCALEDEF_PHOTO,
 BVSCALE_BETTER_DRAWING = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BETTER |
 BVSCALEDEF_DRAWING,
 BVSCALE_BEST = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BEST |
 BVSCALEDEF_DONT_CARE,
 BVSCALE_BEST_POINT_SAMPLE = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BEST |
 BVSCALEDEF_POINT_SAMPLE,
 BVSCALE_BEST_INTERPOLATED = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BEST |
 BVSCALEDEF_INTERPOLATED,
 BVSCALE_BEST_PHOTO = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BEST |
 BVSCALEDEF_PHOTO,
 BVSCALE_BEST_DRAWING = BVSCALEDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_IMPLICIT |
 BVSCALEDEF_BEST |
 BVSCALEDEF_DRAWING,
 BVSCALE_NEAREST_NEIGHBOR = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_NEAREST_NEIGHBOR << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_NEAREST_NEIGHBOR << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_BILINEAR = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_LINEAR << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_LINEAR << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_BICUBIC = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_CUBIC << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_CUBIC << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_3x3_TAP = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_3_TAP << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_3_TAP << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_5x5_TAP = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_5_TAP << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_5_TAP << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_7x7_TAP = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_7_TAP << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_7_TAP << BVSCALEDEF_VERT_SHIFT),
 BVSCALE_9x9_TAP = BVSCALEDEF_VENDOR_GENERIC |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVSCALEDEF_EXPLICIT |
 (BVSCALEDEF_9_TAP << BVSCALEDEF_HORZ_SHIFT) |
 (BVSCALEDEF_9_TAP << BVSCALEDEF_VERT_SHIFT),
#ifdef BVSCALE_EXTERNAL_INCLUDE
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#include BVSCALE_EXTERNAL_INCLUDE
#endif
};
#define BVDITHERDEF_VENDOR_SHIFT 24
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVDITHERDEF_VENDOR_MASK (0xFF << BVDITHERDEF_VENDOR_SHIFT)
#define BVDITHERDEF_VENDOR_ALL (0 << BVDITHERDEF_VENDOR_SHIFT)
#define BVDITHERDEF_VENDOR_TI (1 << BVDITHERDEF_VENDOR_SHIFT)
#define BVDITHERDEF_VENDOR_GENERIC (0xFF << BVDITHERDEF_VENDOR_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVDITHERDEF_TYPE_SHIFT 16
#define BVDITHERDEF_PHOTO (0x01 << BVDITHERDEF_TYPE_SHIFT)
#define BVDITHERDEF_DRAWING (0x02 << BVDITHERDEF_TYPE_SHIFT)
#define BVDITHERDEF_TECHNIQUE_SHIFT 8
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVDITHERDEF_DONT_CARE (0x00 << BVDITHERDEF_TECHNIQUE_SHIFT)
#define BVDITHERDEF_RANDOM (0x01 << BVDITHERDEF_TECHNIQUE_SHIFT)
#define BVDITHERDEF_ORDERED (0x02 << BVDITHERDEF_TECHNIQUE_SHIFT)
#define BVDITHERDEF_DIFFUSED (0x04 << BVDITHERDEF_TECHNIQUE_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVDITHERDEF_ON (0xFF << BVDITHERDEF_TECHNIQUE_SHIFT)
#define BVDITHERDEF_QUALITY_SHIFT 0
#define BVDITHERDEF_FASTEST (0x00 << BVDITHERDEF_QUALITY_SHIFT)
#define BVDITHERDEF_GOOD (0x55 << BVDITHERDEF_QUALITY_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVDITHERDEF_BETTER (0xAA << BVDITHERDEF_QUALITY_SHIFT)
#define BVDITHERDEF_BEST (0xFF << BVDITHERDEF_QUALITY_SHIFT)
enum bvdithermode {
 BVDITHER_FASTEST = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_FASTEST |
 BVDITHERDEF_DONT_CARE,
 BVDITHER_FASTEST_ON = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_FASTEST |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_ON,
 BVDITHER_FASTEST_RANDOM = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_FASTEST |
 BVDITHERDEF_RANDOM,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_FASTEST_ORDERED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_FASTEST |
 BVDITHERDEF_ORDERED,
 BVDITHER_FASTEST_DIFFUSED = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_FASTEST |
 BVDITHERDEF_DIFFUSED,
 BVDITHER_FASTEST_PHOTO = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_FASTEST |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_PHOTO,
 BVDITHER_FASTEST_DRAWING = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_FASTEST |
 BVDITHERDEF_DRAWING,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_GOOD = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_GOOD |
 BVDITHERDEF_DONT_CARE,
 BVDITHER_GOOD_ON = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_GOOD |
 BVDITHERDEF_ON,
 BVDITHER_GOOD_RANDOM = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_GOOD |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_RANDOM,
 BVDITHER_GOOD_ORDERED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_GOOD |
 BVDITHERDEF_ORDERED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_GOOD_DIFFUSED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_GOOD |
 BVDITHERDEF_DIFFUSED,
 BVDITHER_GOOD_PHOTO = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_GOOD |
 BVDITHERDEF_PHOTO,
 BVDITHER_GOOD_DRAWING = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_GOOD |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_DRAWING,
 BVDITHER_BETTER = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BETTER |
 BVDITHERDEF_DONT_CARE,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_BETTER_ON = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BETTER |
 BVDITHERDEF_ON,
 BVDITHER_BETTER_RANDOM = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_BETTER |
 BVDITHERDEF_RANDOM,
 BVDITHER_BETTER_ORDERED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BETTER |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_ORDERED,
 BVDITHER_BETTER_DIFFUSED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BETTER |
 BVDITHERDEF_DIFFUSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_BETTER_PHOTO = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BETTER |
 BVDITHERDEF_PHOTO,
 BVDITHER_BETTER_DRAWING = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_BETTER |
 BVDITHERDEF_DRAWING,
 BVDITHER_BEST = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_DONT_CARE,
 BVDITHER_BEST_ON = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
 BVDITHERDEF_ON,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_BEST_RANDOM = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
 BVDITHERDEF_RANDOM,
 BVDITHER_BEST_ORDERED = BVDITHERDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_BEST |
 BVDITHERDEF_ORDERED,
 BVDITHER_BEST_DIFFUSED = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHERDEF_DIFFUSED,
 BVDITHER_BEST_PHOTO = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
 BVDITHERDEF_PHOTO,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_BEST_DRAWING = BVDITHERDEF_VENDOR_ALL |
 BVDITHERDEF_BEST |
 BVDITHERDEF_DRAWING,
 BVDITHER_NONE = BVDITHERDEF_VENDOR_GENERIC + 0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVDITHER_ORDERED_2x2 = BVDITHERDEF_VENDOR_GENERIC + 4,
 BVDITHER_ORDERED_4x4 = BVDITHERDEF_VENDOR_GENERIC + 16,
 BVDITHER_ORDERED_2x2_4x4 = BVDITHERDEF_VENDOR_GENERIC + 4 + 16,
#ifdef BVDITHER_EXTERNAL_INCLUDE
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#include BVDITHER_EXTERNAL_INCLUDE
#endif
};
#define BVTILE_LEFT_SHIFT 0
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVTILE_TOP_SHIFT (BVTILE_LEFT_SHIFT + 2)
#define BVTILE_RIGHT_SHIFT (BVTILE_TOP_SHIFT + 2)
#define BVTILE_BOTTOM_SHIFT (BVTILE_RIGHT_SHIFT + 2)
#define BVTILE_LEFT_REPEAT (0 << BVTILE_LEFT_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVTILE_TOP_REPEAT (0 << BVTILE_TOP_SHIFT)  
#define BVTILE_RIGHT_REPEAT (0 << BVTILE_RIGHT_SHIFT)  
#define BVTILE_BOTTOM_REPEAT (0 << BVTILE_BOTTOM_SHIFT)  
#define BVTILE_LEFT_MIRROR (1 << BVTILE_LEFT_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVTILE_TOP_MIRROR (1 << BVTILE_TOP_SHIFT)  
#define BVTILE_RIGHT_MIRROR (1 << BVTILE_RIGHT_SHIFT)  
#define BVTILE_BOTTOM_MIRROR (1 << BVTILE_BOTTOM_SHIFT)  
struct bvtileparams {
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 unsigned int structsize;
 unsigned long flags;
 void *virtaddr;
 int dstleft;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 int dsttop;
 unsigned int srcwidth;
 unsigned int srcheight;
};
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_OP 0x00000001  
#define BVBATCH_KEY 0x00000002  
#define BVBATCH_MISCFLAGS 0x00000004  
#define BVBATCH_ALPHA 0x00000008  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_DITHER 0x00000010  
#define BVBATCH_SCALE 0x00000020  
#define BVBATCH_DST 0x00000100  
#define BVBATCH_SRC1 0x00000200  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_SRC2 0x00000400  
#define BVBATCH_MASK 0x00000800  
#define BVBATCH_DSTRECT_ORIGIN 0x00001000  
#define BVBATCH_DSTRECT_SIZE 0x00002000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_SRC1RECT_ORIGIN 0x00004000  
#define BVBATCH_SRC1RECT_SIZE 0x00008000  
#define BVBATCH_SRC2RECT_ORIGIN 0x00010000  
#define BVBATCH_SRC2RECT_SIZE 0x00020000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_MASKRECT_ORIGIN 0x00040000  
#define BVBATCH_MASKRECT_SIZE 0x00080000  
#define BVBATCH_CLIPRECT_ORIGIN 0x00100000  
#define BVBATCH_CLIPRECT_SIZE 0x00200000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_CLIPRECT (BVBATCH_CLIPRECT_ORIGIN |   BVBATCH_CLIPRECT_SIZE)  
#define BVBATCH_TILE_SRC1 0x00400000  
#define BVBATCH_TILE_SRC2 0x00800000  
#define BVBATCH_TILE_MASK 0x00100000  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVBATCH_ENDNOP 0x80000000  
struct bvcallbackerror {
 unsigned int structsize;
 enum bverror error;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 char *errdesc;
};
struct bvbatch;
union bvinbuff {
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 struct bvbuffdesc *desc;
 struct bvtileparams *tileparams;
};
union bvop {
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 unsigned short rop;
 enum bvblend blend;
 struct bvfilter *filter;
};
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
struct bvbltparams {
 unsigned int structsize;
 char *errdesc;
 unsigned long implementation;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 unsigned long flags;
 union bvop op;
 void *colorkey;
 union bvalpha globalalpha;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 enum bvscalemode scalemode;
 enum bvdithermode dithermode;
 struct bvbuffdesc *dstdesc;
 struct bvsurfgeom *dstgeom;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 struct bvrect dstrect;
 union bvinbuff src1;
 struct bvsurfgeom *src1geom;
 struct bvrect src1rect;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 union bvinbuff src2;
 struct bvsurfgeom *src2geom;
 struct bvrect src2rect;
 union bvinbuff mask;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 struct bvsurfgeom *maskgeom;
 struct bvrect maskrect;
 struct bvrect cliprect;
 unsigned long batchflags;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 struct bvbatch *batch;
 void (*callbackfn)(struct bvcallbackerror *err,
 unsigned long callbackdata);
 unsigned long callbackdata;
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
};
#endif
