/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ***   To edit the content of this header, modify the corresponding
 ***   source file (e.g. under external/kernel-headers/original/) then
 ***   run bionic/libc/kernel/tools/update_all.py
 ***
 ***   Any manual change here will be lost the next time this script will
 ***   be run. You've been warned!
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef BVERROR_H
#define BVERROR_H
#define BVERRDEF_VENDOR_SHIFT 24
#define BVERRDEF_VENDOR_MASK (0xFF << BVERRDEF_VENDOR_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define BVERRDEF_VENDOR_ALL (0x00 << BVERRDEF_VENDOR_SHIFT)
#define BVERRDEF_VENDOR_TI (0x01 << BVERRDEF_VENDOR_SHIFT)
enum bverror {
 BVERR_NONE = 0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_UNK =
 BVERRDEF_VENDOR_ALL + 1,
 BVERR_OOM =
 BVERRDEF_VENDOR_ALL + 2,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_RSRC =
 BVERRDEF_VENDOR_ALL + 3,
 BVERR_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 1000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_VIRTPTR =
 BVERR_VIRTADDR,
 BVERR_BUFFERDESC =
 BVERRDEF_VENDOR_ALL + 10000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_BUFFERDESC_VERS =
 BVERRDEF_VENDOR_ALL + 11000,
 BVERR_BUFFERDESC_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 12000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_BUFFERDESC_LEN =
 BVERRDEF_VENDOR_ALL + 13000,
 BVERR_BUFFERDESC_ALIGNMENT =
 BVERRDEF_VENDOR_ALL + 14000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_BLTPARAMS_VERS =
 BVERRDEF_VENDOR_ALL + 20000,
 BVERR_IMPLEMENTATION =
 BVERRDEF_VENDOR_ALL + 21000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_FLAGS =
 BVERRDEF_VENDOR_ALL + 22000,
 BVERR_OP =
 BVERRDEF_VENDOR_ALL + 22100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_KEY =
 BVERRDEF_VENDOR_ALL + 22200,
 BVERR_SRC1_TILE =
 BVERRDEF_VENDOR_ALL + 22300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE =
 BVERRDEF_VENDOR_ALL + 22310,
 BVERR_MASK_TILE =
 BVERRDEF_VENDOR_ALL + 22320,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_FLIP =
 BVERRDEF_VENDOR_ALL + 22400,
 BVERR_ROP =
 BVERRDEF_VENDOR_ALL + 23000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_BLEND =
 BVERRDEF_VENDOR_ALL + 23100,
 BVERR_GLOBAL_ALPHA =
 BVERRDEF_VENDOR_ALL + 23110,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_FILTER =
 BVERRDEF_VENDOR_ALL + 23200,
 BVERR_FILTER_PARAMS_VERS =
 BVERRDEF_VENDOR_ALL + 23210,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_FILTER_PARAMS =
 BVERRDEF_VENDOR_ALL + 23220,
 BVERR_SCALE_MODE =
 BVERRDEF_VENDOR_ALL + 24000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DITHER_MODE =
 BVERRDEF_VENDOR_ALL + 25000,
 BVERR_DSTDESC =
 BVERRDEF_VENDOR_ALL + 26000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DSTDESC_VERS =
 BVERRDEF_VENDOR_ALL + 26100,
 BVERR_DSTDESC_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 26200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DSTDESC_LEN =
 BVERRDEF_VENDOR_ALL + 26300,
 BVERR_DST_ALIGNMENT =
 BVERRDEF_VENDOR_ALL + 26400,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DSTGEOM =
 BVERRDEF_VENDOR_ALL + 27000,
 BVERR_DSTGEOM_VERS =
 BVERRDEF_VENDOR_ALL + 27100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DSTGEOM_FORMAT =
 BVERRDEF_VENDOR_ALL + 27200,
 BVERR_DSTGEOM_STRIDE =
 BVERRDEF_VENDOR_ALL + 27300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_DSTGEOM_PALETTE =
 BVERRDEF_VENDOR_ALL + 27400,
 BVERR_DSTRECT =
 BVERRDEF_VENDOR_ALL + 28000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1DESC =
 BVERRDEF_VENDOR_ALL + 29000,
 BVERR_SRC1DESC_VERS =
 BVERRDEF_VENDOR_ALL + 29100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1DESC_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 29200,
 BVERR_SRC1DESC_LEN =
 BVERRDEF_VENDOR_ALL + 29300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1DESC_ALIGNMENT =
 BVERRDEF_VENDOR_ALL + 29400,
 BVERR_SRC1GEOM =
 BVERRDEF_VENDOR_ALL + 30000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1GEOM_VERS =
 BVERRDEF_VENDOR_ALL + 30100,
 BVERR_SRC1GEOM_FORMAT =
 BVERRDEF_VENDOR_ALL + 30200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1GEOM_STRIDE =
 BVERRDEF_VENDOR_ALL + 30300,
 BVERR_SRC1GEOM_PALETTE =
 BVERRDEF_VENDOR_ALL + 30400,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1RECT =
 BVERRDEF_VENDOR_ALL + 31000,
 BVERR_SRC1_HORZSCALE =
 BVERRDEF_VENDOR_ALL + 31100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_VERTSCALE =
 BVERRDEF_VENDOR_ALL + 31200,
 BVERR_SRC1_ROT =
 BVERRDEF_VENDOR_ALL + 31300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS =
 BVERR_SRC1DESC,
 BVERR_SRC1_TILE_VERS =
 BVERRDEF_VENDOR_ALL + 32000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS_VERS =
 BVERR_SRC1_TILE_VERS,
 BVERR_SRC1_TILE_FLAGS =
 BVERRDEF_VENDOR_ALL + 32100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS_FLAGS =
 BVERR_SRC1_TILE_FLAGS,
 BVERR_SRC1_TILE_VIRTADDR =
 BVERR_SRC1DESC_VIRTADDR,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS_VIRTADDR =
 BVERR_SRC1_TILE_VIRTADDR,
 BVERR_SRC1_TILE_ORIGIN =
 BVERRDEF_VENDOR_ALL + 32200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS_ORIGIN =
 BVERR_SRC1_TILE_ORIGIN,
 BVERR_SRC1_TILE_SIZE =
 BVERRDEF_VENDOR_ALL + 32300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC1_TILEPARAMS_SIZE =
 BVERR_SRC1_TILE_SIZE,
 BVERR_SRC2DESC =
 BVERRDEF_VENDOR_ALL + 33000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2DESC_VERS =
 BVERRDEF_VENDOR_ALL + 33100,
 BVERR_SRC2DESC_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 33200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2DESC_LEN =
 BVERRDEF_VENDOR_ALL + 33300,
 BVERR_SRC2DESC_ALIGNMENT =
 BVERRDEF_VENDOR_ALL + 33400,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2GEOM =
 BVERRDEF_VENDOR_ALL + 34000,
 BVERR_SRC2GEOM_VERS =
 BVERRDEF_VENDOR_ALL + 34100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2GEOM_FORMAT =
 BVERRDEF_VENDOR_ALL + 34200,
 BVERR_SRC2GEOM_STRIDE =
 BVERRDEF_VENDOR_ALL + 34300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2GEOM_PALETTE =
 BVERRDEF_VENDOR_ALL + 34400,
 BVERR_SRC2RECT =
 BVERRDEF_VENDOR_ALL + 35000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_HORZSCALE =
 BVERRDEF_VENDOR_ALL + 35100,
 BVERR_SRC2_VERTSCALE =
 BVERRDEF_VENDOR_ALL + 35200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_ROT =
 BVERRDEF_VENDOR_ALL + 35300,
 BVERR_SRC2_TILEPARAMS =
 BVERR_SRC2DESC,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE_VERS =
 BVERRDEF_VENDOR_ALL + 36000,
 BVERR_SRC2_TILEPARAMS_VERS =
 BVERR_SRC2_TILE_VERS,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE_FLAGS =
 BVERRDEF_VENDOR_ALL + 36100,
 BVERR_SRC2_TILEPARAMS_FLAGS =
 BVERR_SRC2_TILE_FLAGS,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE_VIRTADDR =
 BVERR_SRC2DESC_VIRTADDR,
 BVERR_SRC2_TILEPARAMS_VIRTADDR =
 BVERR_SRC2_TILE_VIRTADDR,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE_ORIGIN =
 BVERRDEF_VENDOR_ALL + 36200,
 BVERR_SRC2_TILEPARAMS_ORIGIN =
 BVERR_SRC2_TILE_ORIGIN,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_SRC2_TILE_SIZE =
 BVERRDEF_VENDOR_ALL + 36300,
 BVERR_SRC2_TILEPARAMS_SIZE =
 BVERR_SRC2_TILE_SIZE,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKDESC =
 BVERRDEF_VENDOR_ALL + 37000,
 BVERR_MASKDESC_VERS =
 BVERRDEF_VENDOR_ALL + 37100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKDESC_VIRTADDR =
 BVERRDEF_VENDOR_ALL + 37200,
 BVERR_MASKDESC_LEN =
 BVERRDEF_VENDOR_ALL + 37300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKDESC_ALIGNMENT =
 BVERRDEF_VENDOR_ALL + 37400,
 BVERR_MASKGEOM =
 BVERRDEF_VENDOR_ALL + 38000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKGEOM_VERS =
 BVERRDEF_VENDOR_ALL + 38100,
 BVERR_MASKGEOM_FORMAT =
 BVERRDEF_VENDOR_ALL + 38200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKGEOM_STRIDE =
 BVERRDEF_VENDOR_ALL + 38300,
 BVERR_MASKGEOM_PALETTE =
 BVERRDEF_VENDOR_ALL + 38400,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASKRECT =
 BVERRDEF_VENDOR_ALL + 39000,
 BVERR_MASK_HORZSCALE =
 BVERRDEF_VENDOR_ALL + 39100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_VERTSCALE =
 BVERRDEF_VENDOR_ALL + 39200,
 BVERR_MASK_ROT =
 BVERRDEF_VENDOR_ALL + 39300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS =
 BVERR_MASKDESC,
 BVERR_MASK_TILE_VERS =
 BVERRDEF_VENDOR_ALL + 40000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS_VERS =
 BVERR_MASK_TILE_VERS,
 BVERR_MASK_TILE_FLAGS =
 BVERRDEF_VENDOR_ALL + 40100,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS_FLAGS =
 BVERR_MASK_TILE_FLAGS,
 BVERR_MASK_TILE_VIRTADDR =
 BVERR_MASKDESC_VIRTADDR,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS_VIRTADDR =
 BVERR_MASK_TILE_VIRTADDR,
 BVERR_MASK_TILE_ORIGIN =
 BVERRDEF_VENDOR_ALL + 40200,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS_ORIGIN =
 BVERR_MASK_TILE_ORIGIN,
 BVERR_MASK_TILE_SIZE =
 BVERRDEF_VENDOR_ALL + 40300,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MASK_TILEPARAMS_SIZE =
 BVERR_MASK_TILE_SIZE,
 BVERR_CLIP_RECT =
 BVERRDEF_VENDOR_ALL + 41000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_BATCH_FLAGS =
 BVERRDEF_VENDOR_ALL + 42000,
 BVERR_BATCH =
 BVERRDEF_VENDOR_ALL + 43000,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_OP_FAILED =
 BVERRDEF_VENDOR_ALL + 50000,
 BVERR_OP_INCOMPLETE =
 BVERRDEF_VENDOR_ALL + 50001,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 BVERR_MEMORY_ERROR =
 BVERRDEF_VENDOR_ALL + 51000,
#ifdef BVERR_EXTERNAL_INCLUDE
#include BVERR_EXTERNAL_INCLUDE
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#endif
};
#endif
