/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ***   To edit the content of this header, modify the corresponding
 ***   source file (e.g. under external/kernel-headers/original/) then
 ***   run bionic/libc/kernel/tools/update_all.py
 ***
 ***   Any manual change here will be lost the next time this script will
 ***   be run. You've been warned!
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef OCD_H
#define OCD_H
#define OCDFMTDEF_VENDOR_SHIFT 24
#define OCDFMTDEF_VENDOR_MASK (0xFF << OCDFMTDEF_VENDOR_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_VENDOR_ALL   (0x00 << OCDFMTDEF_VENDOR_SHIFT)  
#define OCDFMTDEF_VENDOR_TI   (0x01 << OCDFMTDEF_VENDOR_SHIFT)  
#define OCDFMTDEF_CS_SHIFT 21
#define OCDFMTDEF_CS_MASK (7 << OCDFMTDEF_CS_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_CS_MONO   (0 << OCDFMTDEF_CS_SHIFT)  
#define OCDFMTDEF_CS_LUT   (1 << OCDFMTDEF_CS_SHIFT)  
#define OCDFMTDEF_CS_RGB   (2 << OCDFMTDEF_CS_SHIFT)  
#define OCDFMTDEF_CS_YCbCr   (3 << OCDFMTDEF_CS_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_CS_ALPHA   (4 << OCDFMTDEF_CS_SHIFT)  
#define OCDFMTDEF_STD_SHIFT 19
#define OCDFMTDEF_STD_MASK (3 << OCDFMTDEF_STD_SHIFT)
#define OCDFMTDEF_STD_ITUR_601_YCbCr   (0 << OCDFMTDEF_STD_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_STD_ITUR_709_YCbCr   (1 << OCDFMTDEF_STD_SHIFT)  
#define OCDFMTDEF_FULLSCALE_YCbCr   (3 << OCDFMTDEF_STD_SHIFT)  
#define OCDFMTDEF_ALPHA   (1 << 18)  
#define OCDFMTDEF_NON_PREMULT   (1 << 17)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_FILL_EMPTY_0   (1 << 17)  
#define OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED   (0 << 16)  
#define OCDFMTDEF_SUBSAMPLE_HORZ_CENTERED   (1 << 16)  
#define OCDFMTDEF_ALPHA_COMPONENTS_SHIFT 16
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_ALPHA_COMPONENTS_MASK (3 << OCDFMTDEF_ALPHA_COMPONENTS_SHIFT)
#define OCDFMTDEF_ALPHA_COMPONENTS_1 (0 << OCDFMTDEF_ALPHA_COMPONENTS_SHIFT)
#define OCDFMTDEF_ALPHA_COMPONENTS_2 (1 << OCDFMTDEF_ALPHA_COMPONENTS_SHIFT)
#define OCDFMTDEF_ALPHA_COMPONENTS_3 (2 << OCDFMTDEF_ALPHA_COMPONENTS_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_ALPHA_COMPONENTS_4 (3 << OCDFMTDEF_ALPHA_COMPONENTS_SHIFT)
#define OCDFMTDEF_SUBSAMPLE_SHIFT 14
#define OCDFMTDEF_SUBSAMPLE_MASK (3 << OCDFMTDEF_SUBSAMPLE_SHIFT)
#define OCDFMTDEF_SUBSAMPLE_NONE   (0 << OCDFMTDEF_SUBSAMPLE_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_SUBSAMPLE_422_YCbCr   (1 << OCDFMTDEF_SUBSAMPLE_SHIFT)  
#define OCDFMTDEF_SUBSAMPLE_420_YCbCr   (2 << OCDFMTDEF_SUBSAMPLE_SHIFT)  
#define OCDFMTDEF_SUBSAMPLE_411_YCbCr   (3 << OCDFMTDEF_SUBSAMPLE_SHIFT)  
#define OCDFMTDEF_LAYOUT_SHIFT 11
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_LAYOUT_MASK (7 << OCDFMTDEF_LAYOUT_SHIFT)
#define OCDFMTDEF_PACKED   (0 << OCDFMTDEF_LAYOUT_SHIFT)  
#define OCDFMTDEF_DISTRIBUTED   (1 << OCDFMTDEF_LAYOUT_SHIFT)  
#define OCDFMTDEF_2_PLANE_YCbCr   (2 << OCDFMTDEF_LAYOUT_SHIFT)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_3_PLANE_STACKED   (3 << OCDFMTDEF_LAYOUT_SHIFT)  
#define OCDFMTDEF_3_PLANE_SIDE_BY_SIDE_YCbCr   (7 << OCDFMTDEF_LAYOUT_SHIFT)  
#define OCDFMTDEF_REVERSED   (1 << 10)  
#define OCDFMTDEF_LEFT_JUSTIFIED   (1 << 9)  
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_CONTAINER_SHIFT 6
#define OCDFMTDEF_CONTAINER_MASK (7 << OCDFMTDEF_CONTAINER_SHIFT)
#define OCDFMTDEF_CONTAINER_8BIT (0 << OCDFMTDEF_CONTAINER_SHIFT)
#define OCDFMTDEF_CONTAINER_16BIT (1 << OCDFMTDEF_CONTAINER_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_CONTAINER_24BIT (2 << OCDFMTDEF_CONTAINER_SHIFT)
#define OCDFMTDEF_CONTAINER_32BIT (3 << OCDFMTDEF_CONTAINER_SHIFT)
#define OCDFMTDEF_CONTAINER_48BIT (5 << OCDFMTDEF_CONTAINER_SHIFT)
#define OCDFMTDEF_CONTAINER_64BIT (7 << OCDFMTDEF_CONTAINER_SHIFT)
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#define OCDFMTDEF_COMPONENTSIZEMINUS1_SHIFT 0
#define OCDFMTDEF_COMPONENTSIZEMINUS1_MASK   (0x3F << OCDFMTDEF_COMPONENTSIZEMINUS1_SHIFT)
enum ocdformat {
 OCDFMT_UNKNOWN = -1,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NONE = OCDFMT_UNKNOWN,
 OCDFMT_ALPHA1 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_1 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (1 - 1),
 OCDFMT_ALPHA2 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_1 |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (2 - 1),
 OCDFMT_ALPHA4 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_1 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (4 - 1),
 OCDFMT_ALPHA8 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_1 |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (8 - 1),
 OCDFMT_ALPHA4x1 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_4 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (4 - 1),
 OCDFMT_ALPHA3x8 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_3 |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_24BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (24 - 1),
 OCDFMT_ALPHA4x8 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_ALPHA |
 OCDFMTDEF_ALPHA_COMPONENTS_4 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_32BIT |
 (32 - 1),
 OCDFMT_MONO1 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_MONO |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (1 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_MONO2 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_MONO |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (2 - 1),
 OCDFMT_MONO4 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_MONO |
 OCDFMTDEF_PACKED |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CONTAINER_8BIT |
 (4 - 1),
 OCDFMT_MONO8 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_MONO |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (8 - 1),
 OCDFMT_LUT1 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_LUT |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (1 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_LUT2 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_LUT |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (2 - 1),
 OCDFMT_LUT4 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_LUT |
 OCDFMTDEF_PACKED |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CONTAINER_8BIT |
 (4 - 1),
 OCDFMT_LUT8 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_LUT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_8BIT |
 (8 - 1),
 OCDFMT_RGB12 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_RGB |
 OCDFMTDEF_SUBSAMPLE_NONE |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_16BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (12 - 1),
 OCDFMT_xRGB12 = OCDFMT_RGB12,
 OCDFMT_1RGB12 = OCDFMT_xRGB12,
 OCDFMT_0RGB12 = OCDFMT_xRGB12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_BGR12 = OCDFMT_RGB12 |
 OCDFMTDEF_REVERSED,
 OCDFMT_xBGR12 = OCDFMT_BGR12,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_1BGR12 = OCDFMT_xBGR12,
 OCDFMT_0BGR12 = OCDFMT_xBGR12 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_RGBx12 = OCDFMT_xRGB12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_RGB112 = OCDFMT_RGBx12,
 OCDFMT_RGB012 = OCDFMT_RGBx12 |
 OCDFMTDEF_FILL_EMPTY_0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGRx12 = OCDFMT_xRGB12 |
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_REVERSED,
 OCDFMT_BGR112 = OCDFMT_BGRx12,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGR012 = OCDFMT_BGRx12 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_RGB15 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_NONE |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_16BIT |
 (15 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_xRGB15 = OCDFMT_RGB15,
 OCDFMT_1RGB15 = OCDFMT_xRGB15,
 OCDFMT_0RGB15 = OCDFMT_xRGB15 |
 OCDFMTDEF_FILL_EMPTY_0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGR15 = OCDFMT_RGB15 |
 OCDFMTDEF_REVERSED,
 OCDFMT_xBGR15 = OCDFMT_BGR15,
 OCDFMT_1BGR15 = OCDFMT_xBGR15,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_0BGR15 = OCDFMT_xBGR15 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_RGBx15 = OCDFMT_RGB15 |
 OCDFMTDEF_LEFT_JUSTIFIED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_RGB115 = OCDFMT_RGBx15,
 OCDFMT_RGB015 = OCDFMT_RGBx15 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_BGRx15 = OCDFMT_RGB15 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_REVERSED,
 OCDFMT_BGR115 = OCDFMT_BGRx15,
 OCDFMT_BGR015 = OCDFMT_BGRx15 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_RGB16 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
 OCDFMTDEF_SUBSAMPLE_NONE |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_16BIT |
 (16 - 1),
 OCDFMT_BGR16 = OCDFMT_RGB16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_RGB24 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
 OCDFMTDEF_SUBSAMPLE_NONE |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_24BIT |
 (24 - 1),
 OCDFMT_BGR24 = OCDFMT_RGB24 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_xRGB16 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
 OCDFMTDEF_SUBSAMPLE_NONE |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_24BIT |
 (16 - 1),
 OCDFMT_1RGB16 = OCDFMT_xRGB16,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_0RGB16 = OCDFMT_xRGB16 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_xBGR16 = OCDFMT_xRGB16 |
 OCDFMTDEF_REVERSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_1BGR16 = OCDFMT_xBGR16,
 OCDFMT_0BGR16 = OCDFMT_xBGR16 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_RGBx16 = OCDFMT_xRGB16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_RGB116 = OCDFMT_RGBx16,
 OCDFMT_RGB016 = OCDFMT_RGBx16 |
 OCDFMTDEF_FILL_EMPTY_0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGRx16 = OCDFMT_xRGB16 |
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_REVERSED,
 OCDFMT_BGR116 = OCDFMT_BGRx16,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGR016 = OCDFMT_BGRx16 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_xRGB24 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_NONE |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_32BIT |
 (24 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_1RGB24 = OCDFMT_xRGB24,
 OCDFMT_0RGB24 = OCDFMT_xRGB24 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_xBGR24 = OCDFMT_xRGB24 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_1BGR24 = OCDFMT_xBGR24,
 OCDFMT_0BGR24 = OCDFMT_xBGR24 |
 OCDFMTDEF_FILL_EMPTY_0,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_RGBx24 = OCDFMT_xRGB24 |
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_RGB124 = OCDFMT_RGBx24,
 OCDFMT_RGB024 = OCDFMT_RGBx24 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_BGRx24 = OCDFMT_xRGB24 |
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_REVERSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_BGR124 = OCDFMT_BGRx24,
 OCDFMT_BGR024 = OCDFMT_BGRx24 |
 OCDFMTDEF_FILL_EMPTY_0,
 OCDFMT_ARGB12 = OCDFMT_xRGB12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_ALPHA,
 OCDFMT_ABGR12 = OCDFMT_xBGR12 |
 OCDFMTDEF_ALPHA,
 OCDFMT_RGBA12 = OCDFMT_RGBx12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_ALPHA,
 OCDFMT_BGRA12 = OCDFMT_BGRx12 |
 OCDFMTDEF_ALPHA,
 OCDFMT_ARGB16 = OCDFMT_xRGB16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_ALPHA,
 OCDFMT_ABGR16 = OCDFMT_ARGB16 |
 OCDFMTDEF_REVERSED,
 OCDFMT_RGBA16 = OCDFMT_ARGB16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_BGRA16 = OCDFMT_ARGB16 |
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_REVERSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_ARGB24 = OCDFMT_xRGB24 |
 OCDFMTDEF_ALPHA,
 OCDFMT_ABGR24 = OCDFMT_xBGR24 |
 OCDFMTDEF_ALPHA,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_RGBA24 = OCDFMT_RGBx24 |
 OCDFMTDEF_ALPHA,
 OCDFMT_BGRA24 = OCDFMT_BGRx24 |
 OCDFMTDEF_ALPHA,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nARGB12 = OCDFMT_ARGB12 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_ARGB12_NON_PREMULT = OCDFMT_nARGB12,
 OCDFMT_nABGR12 = OCDFMT_ABGR12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_ABGR12_NON_PREMULT = OCDFMT_nABGR12,
 OCDFMT_nRGBA12 = OCDFMT_RGBA12 |
 OCDFMTDEF_NON_PREMULT,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_RGBA12_NON_PREMULT = OCDFMT_nRGBA12,
 OCDFMT_nBGRA12 = OCDFMT_BGRA12 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_BGRA12_NON_PREMULT = OCDFMT_nBGRA12,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_ARGB15 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_RGB |
 OCDFMTDEF_ALPHA |
 OCDFMTDEF_NON_PREMULT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_NONE |
 OCDFMTDEF_PACKED |
 OCDFMTDEF_CONTAINER_16BIT |
 (15 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nARGB15 = OCDFMT_ARGB15,
 OCDFMT_ARGB15_NON_PREMULT = OCDFMT_nARGB15,
 OCDFMT_ABGR15 = OCDFMT_ARGB15 |
 OCDFMTDEF_REVERSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nABGR15 = OCDFMT_ABGR15,
 OCDFMT_ABGR15_NON_PREMULT = OCDFMT_nABGR15,
 OCDFMT_RGBA15 = OCDFMT_ARGB15 |
 OCDFMTDEF_LEFT_JUSTIFIED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nRGBA15 = OCDFMT_RGBA15,
 OCDFMT_RGBA15_NON_PREMULT = OCDFMT_nRGBA15,
 OCDFMT_BGRA15 = OCDFMT_ARGB15 |
 OCDFMTDEF_LEFT_JUSTIFIED |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_nBGRA15 = OCDFMT_BGRA15,
 OCDFMT_BGRA15_NON_PREMULT = OCDFMT_nRGBA15,
 OCDFMT_nARGB16 = OCDFMT_ARGB16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_ARGB16_NON_PREMULT = OCDFMT_nARGB16,
 OCDFMT_nABGR16 = OCDFMT_ABGR16 |
 OCDFMTDEF_NON_PREMULT,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_ABGR16_NON_PREMULT = OCDFMT_nABGR16,
 OCDFMT_nRGBA16 = OCDFMT_RGBA16 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_RGBA16_NON_PREMULT = OCDFMT_nRGBA16,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nBGRA16 = OCDFMT_BGRA16 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_BGRA16_NON_PREMULT = OCDFMT_nBGRA16,
 OCDFMT_nARGB24 = OCDFMT_ARGB24 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_ARGB24_NON_PREMULT = OCDFMT_nARGB24,
 OCDFMT_nABGR24 = OCDFMT_ABGR24 |
 OCDFMTDEF_NON_PREMULT,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_ABGR24_NON_PREMULT = OCDFMT_nABGR24,
 OCDFMT_nRGBA24 = OCDFMT_RGBA24 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_RGBA24_NON_PREMULT = OCDFMT_nRGBA24,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_nBGRA24 = OCDFMT_BGRA24 |
 OCDFMTDEF_NON_PREMULT,
 OCDFMT_BGRA24_NON_PREMULT = OCDFMT_nBGRA24,
 OCDFMT_UYVY = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_YCbCr |
 OCDFMTDEF_SUBSAMPLE_422_YCbCr |
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_PACKED |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CONTAINER_32BIT |
 (16 - 1),
 OCDFMT_UYVY_601 = OCDFMT_UYVY |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_UYVY_709 = OCDFMT_UYVY |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_Y422 = OCDFMT_UYVY,
 OCDFMT_Y422_601 = OCDFMT_UYVY_601,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_Y422_709 = OCDFMT_UYVY_709,
 OCDFMT_VYUY = OCDFMT_UYVY |
 OCDFMTDEF_REVERSED,
 OCDFMT_VYUY_601 = OCDFMT_VYUY |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_VYUY_709 = OCDFMT_VYUY |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_YUYV = OCDFMT_UYVY |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_YUYV_601 = OCDFMT_YUYV |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_YUYV_709 = OCDFMT_YUYV |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_YUY2 = OCDFMT_YUYV,
 OCDFMT_YUY2_601 = OCDFMT_YUYV_601,
 OCDFMT_YUY2_709 = OCDFMT_YUYV_709,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_YVYU = OCDFMT_VYUY |
 OCDFMTDEF_LEFT_JUSTIFIED,
 OCDFMT_YVYU_601 = OCDFMT_YVYU |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_YVYU_709 = OCDFMT_YVYU |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_YV16 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_422_YCbCr |
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_3_PLANE_STACKED |
 OCDFMTDEF_CONTAINER_32BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (16 - 1),
 OCDFMT_YV16_601 = OCDFMT_YV16 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_YV16_709 = OCDFMT_YV16 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_IYUV = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_YCbCr |
 OCDFMTDEF_SUBSAMPLE_420_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_3_PLANE_STACKED |
 OCDFMTDEF_CONTAINER_48BIT |
 (12 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_IYUV_601 = OCDFMT_IYUV |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_IYUV_709 = OCDFMT_IYUV |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_I420 = OCDFMT_IYUV,
 OCDFMT_I420_601 = OCDFMT_IYUV_601,
 OCDFMT_I420_709 = OCDFMT_IYUV_709,
 OCDFMT_YV12 = OCDFMT_IYUV |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_YV12_601 = OCDFMT_YV12 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_YV12_709 = OCDFMT_YV12 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_IMC3 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_YCbCr |
 OCDFMTDEF_SUBSAMPLE_420_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_3_PLANE_STACKED |
 OCDFMTDEF_LEFT_JUSTIFIED |
 OCDFMTDEF_CONTAINER_48BIT |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 (12 - 1),
 OCDFMT_IMC3_601 = OCDFMT_IMC3 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_IMC3_709 = OCDFMT_IMC3 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_IMC1 = OCDFMT_IMC3 |
 OCDFMTDEF_REVERSED,
 OCDFMT_IMC1_601 = OCDFMT_IMC1 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_IMC1_709 = OCDFMT_IMC1 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_IMC4 = OCDFMTDEF_VENDOR_ALL |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CS_YCbCr |
 OCDFMTDEF_STD_ITUR_601_YCbCr |
 OCDFMTDEF_SUBSAMPLE_420_YCbCr |
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_3_PLANE_SIDE_BY_SIDE_YCbCr |
 OCDFMTDEF_CONTAINER_48BIT |
 (12 - 1),
 OCDFMT_IMC4_601 = OCDFMT_IMC4 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_IMC4_709 = OCDFMT_IMC4 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_IMC2 = OCDFMT_IMC4 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_REVERSED,
 OCDFMT_IMC2_601 = OCDFMT_IMC2 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_IMC2_709 = OCDFMT_IMC2 |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_NV16 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_YCbCr |
 OCDFMTDEF_SUBSAMPLE_422_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_2_PLANE_YCbCr |
 OCDFMTDEF_CONTAINER_32BIT |
 (16 - 1),
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NV16_601 = OCDFMT_NV16 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_NV16_709 = OCDFMT_NV16 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NV61 = OCDFMT_NV16 |
 OCDFMTDEF_REVERSED,
 OCDFMT_NV61_601 = OCDFMT_NV61 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NV61_709 = OCDFMT_NV61 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_NV12 = OCDFMTDEF_VENDOR_ALL |
 OCDFMTDEF_CS_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_STD_ITUR_601_YCbCr |
 OCDFMTDEF_SUBSAMPLE_420_YCbCr |
 OCDFMTDEF_SUBSAMPLE_HORZ_ALIGNED |
 OCDFMTDEF_2_PLANE_YCbCr |
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMTDEF_CONTAINER_48BIT |
 (12 - 1),
 OCDFMT_NV12_601 = OCDFMT_NV12 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NV12_709 = OCDFMT_NV12 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
 OCDFMT_NV21 = OCDFMT_NV12 |
 OCDFMTDEF_REVERSED,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
 OCDFMT_NV21_601 = OCDFMT_NV21 |
 OCDFMTDEF_STD_ITUR_601_YCbCr,
 OCDFMT_NV21_709 = OCDFMT_NV21 |
 OCDFMTDEF_STD_ITUR_709_YCbCr,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#ifdef OCD_EXTERNAL_INCLUDE
#include OCD_EXTERNAL_INCLUDE
#endif
};
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
#endif
