#
# Do not Edit! Generated by:
# spectacle version 0.16
#
# >> macros
%define drimoduledir	%{_libdir}/dri
%define fwdir		/lib/firmware
# << macros

Name:       psb-video
Summary:    mrst/mfld gfx video drivers for X11
Version:    5.3.0.0035
Release:    1
Group:      System/Libraries
License:    Intel Proprietary
URL:        http://freedesktop.org/wiki/Software/vaapi
Source0:    %{name}-%{version}.tar.bz2
NoSource:   0
AutoReqProv: no
Requires:   xorg-x11-server-Xorg
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xv)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(xrender)
BuildRequires:  pkgconfig(xorg-server)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(libwsbm)
BuildRequires:  pkgconfig(libva)
BuildRequires:  kernel-staging-drivers-headers
BuildRequires:  libmemrar-devel
BuildRequires:	pvr-bin-UMG pvr-bin-UMG-compatlibs
BuildRequires:  libtool
Requires:	pvr-bin-UMG pvr-bin-UMG-compatlibs

%description
mrst/mfld video x11 drivers


%prep
%setup -q

# >> setup
# << setup

%build
# >> build pre
unset LD_AS_NEEDED
# << build pre

./autogen.sh
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig




%files
%defattr(-,root,root,-)
# >> files
%{drimoduledir}/pvr_drv_video.so
%{fwdir}/*.bin
# << files
